/* kbs_ssh_config.h.  Generated by configure.  */
/* kbs_ssh_config.h.in.  Generated from configure.ac by autoheader.  */


#ifndef KBS_SSH_CONFIG_H_INCLUDED
#define KBS_SSH_CONFIG_H_INCLUDED


/* */
/* #undef ALLOW_GROUP_WRITEABILITY */

/* */
/* #undef BROKEN_INET_ADDR */

/* */
/* #undef DEFAULT_PATH */

/* */
/* #undef ENABLE_SO_LINGER */

/* */
#define ENABLE_TCP_NODELAY 1

/* */
#define HAVE_ADDR_IN_UTMP 1

/* Define to 1 if you have the `authenticate' function. */
/* #undef HAVE_AUTHENTICATE */

/* Define to 1 if you have the `clock' function. */
#define HAVE_CLOCK 1

/* Define to 1 if you have the `crypt' function. */
#define HAVE_CRYPT 1

/* Define to 1 if you have the `daemon' function. */
#define HAVE_DAEMON 1

/* */
#define HAVE_DEV_PTMX 1

/* */
/* #undef HAVE_DEV_PTS_AND_PTC */

/* */
/* #undef HAVE_DEV_PTYP10 */

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* */
/* #undef HAVE_ETC_DEFAULT_LOGIN */

/* */
/* #undef HAVE_ETC_SECURITY_PASSWD */

/* */
/* #undef HAVE_ETC_SECURITY_PASSWD_ADJUNCT */

/* */
#define HAVE_ETC_SHADOW 1

/* Define to 1 if you have the `fchmod' function. */
#define HAVE_FCHMOD 1

/* Define to 1 if you have the `ftruncate' function. */
#define HAVE_FTRUNCATE 1

/* Define to 1 if you have the `getdtablesize' function. */
#define HAVE_GETDTABLESIZE 1

/* Define to 1 if you have the `gethostname' function. */
#define HAVE_GETHOSTNAME 1

/* */
/* #undef HAVE_GETPSEUDOTTY */

/* Define to 1 if you have the `getpt' function. */
#define HAVE_GETPT 1

/* Define to 1 if you have the `getrusage' function. */
#define HAVE_GETRUSAGE 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* */
#define HAVE_HOST_IN_UTMP 1

/* */
/* #undef HAVE_HPUX_TCB_AUTH */

/* */
#define HAVE_ID_IN_UTMP 1

/* */
/* #undef HAVE_INCOMPATIBLE_SIGINFO */

/* Define to 1 if you have the `initgroups' function. */
#define HAVE_INITGROUPS 1

/* Define to 1 if you have the `innetgr' function. */
#define HAVE_INNETGR 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `isastream' function. */
#define HAVE_ISASTREAM 1

/* */
#define HAVE_LASTLOG 1

/* Define to 1 if you have the <lastlog.h> header file. */
#define HAVE_LASTLOG_H 1

/* Define to 1 if you have the `aud' library (-laud). */
/* #undef HAVE_LIBAUD */

/* Define to 1 if you have the `auth' library (-lauth). */
/* #undef HAVE_LIBAUTH */

/* Define to 1 if you have the `bsd' library (-lbsd). */
#define HAVE_LIBBSD 1

/* Define to 1 if you have the `crypt' library (-lcrypt). */
#define HAVE_LIBCRYPT 1

/* Define to 1 if you have the `db' library (-ldb). */
/* #undef HAVE_LIBDB */

/* */
/* #undef HAVE_LIBESMTP */

/* Define to 1 if you have the `gen' library (-lgen). */
/* #undef HAVE_LIBGEN */

/* Define to 1 if you have the `inet' library (-linet). */
/* #undef HAVE_LIBINET */

/* Define to 1 if you have the `m' library (-lm). */
/* #undef HAVE_LIBM */

/* Define to 1 if you have the `nsl' library (-lnsl). */
#define HAVE_LIBNSL 1

/* Define to 1 if you have the `s' library (-ls). */
/* #undef HAVE_LIBS */

/* Define to 1 if you have the `sec' library (-lsec). */
/* #undef HAVE_LIBSEC */

/* Define to 1 if you have the `security' library (-lsecurity). */
/* #undef HAVE_LIBSECURITY */

/* Define to 1 if you have the `seq' library (-lseq). */
/* #undef HAVE_LIBSEQ */

/* Define to 1 if you have the `shadow' library (-lshadow). */
/* #undef HAVE_LIBSHADOW */

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define to 1 if you have the `sun' library (-lsun). */
/* #undef HAVE_LIBSUN */

/* */
#define HAVE_LIBUTIL_LOGIN 1

/* */
/* #undef HAVE_LIBWRAP */

/* Define to 1 if you have the <login_cap.h> header file. */
/* #undef HAVE_LOGIN_CAP_H */

/* Define to 1 if you have the <machine/endian.h> header file. */
/* #undef HAVE_MACHINE_ENDIAN_H */

/* Define to 1 if you have the `makeutx' function. */
/* #undef HAVE_MAKEUTX */

/* Define to 1 if you have the `memcpy' function. */
#define HAVE_MEMCPY 1

/* Define to 1 if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Enable MySQL support */
#define HAVE_MYSQL_SMTH 1

/* */
#define HAVE_NAME_IN_UTMP 1

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <netinet/in_system.h> header file. */
/* #undef HAVE_NETINET_IN_SYSTEM_H */

/* Define to 1 if you have the <netinet/in_systm.h> header file. */
#define HAVE_NETINET_IN_SYSTM_H 1

/* Define to 1 if you have the <netinet/ip.h> header file. */
#define HAVE_NETINET_IP_H 1

/* Define to 1 if you have the <netinet/tcp.h> header file. */
#define HAVE_NETINET_TCP_H 1

/* */
/* #undef HAVE_NO_TZ_IN_GETTIMEOFDAY */

/* Define to 1 if you have the `openpty' function. */
#define HAVE_OPENPTY 1

/* Define to 1 if you have the <paths.h> header file. */
#define HAVE_PATHS_H 1

/* */
#define HAVE_PID_IN_UTMP 1

/* Define to 1 if you have the `putenv' function. */
#define HAVE_PUTENV 1

/* Define to 1 if you have the `pw_encrypt' function. */
/* #undef HAVE_PW_ENCRYPT */

/* Define to 1 if you have the `random' function. */
#define HAVE_RANDOM 1

/* Define to 1 if you have the `remove' function. */
#define HAVE_REMOVE 1

/* Define to 1 if you have the `revoke' function. */
/* #undef HAVE_REVOKE */

/* Define to 1 if you have the <rusage.h> header file. */
/* #undef HAVE_RUSAGE_H */

/* */
/* #undef HAVE_SCO_ETC_SHADOW */

/* */
/* #undef HAVE_SECURID */

/* Define to 1 if you have the `setlogin' function. */
/* #undef HAVE_SETLOGIN */

/* Define to 1 if you have the `setluid' function. */
/* #undef HAVE_SETLUID */

/* Define to 1 if you have the `setpgid' function. */
#define HAVE_SETPGID 1

/* Define to 1 if you have the `setpgrp' function. */
#define HAVE_SETPGRP 1

/* Define to 1 if you have the `setsid' function. */
#define HAVE_SETSID 1

/* */
/* #undef HAVE_SGI_PROJ_H */

/* Define to 1 if you have the <sgtty.h> header file. */
#define HAVE_SGTTY_H 1

/* Define to 1 if you have the <shadow.h> header file. */
#define HAVE_SHADOW_H 1

/* */
/* #undef HAVE_SIA */

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the `socketpair' function. */
#define HAVE_SOCKETPAIR 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* */
/* #undef HAVE_STRUCT_SPWD_EXPIRE */

/* */
/* #undef HAVE_STRUCT_SPWD_INACT */

/* Define to 1 if `st_blksize' is member of `struct stat'. */
#define HAVE_STRUCT_STAT_ST_BLKSIZE 1

/* Define to 1 if your `struct stat' has `st_blksize'. Deprecated, use
   `HAVE_STRUCT_STAT_ST_BLKSIZE' instead. */
#define HAVE_ST_BLKSIZE 1

/* */
/* #undef HAVE_SYSLEN_IN_UTMPX */

/* Define to 1 if you have the <sys/conf.h> header file. */
/* #undef HAVE_SYS_CONF_H */

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/stream.h> header file. */
/* #undef HAVE_SYS_STREAM_H */

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <termios.h> header file. */
#define HAVE_TERMIOS_H 1

/* Define to 1 if you have the `times' function. */
#define HAVE_TIMES 1

/* */
/* #undef HAVE_TIS */

/* Define to 1 if you have the `ttyslot' function. */
#define HAVE_TTYSLOT 1

/* Define to 1 if you have the `ulimit' function. */
#define HAVE_ULIMIT 1

/* Define to 1 if you have the <ulimit.h> header file. */
#define HAVE_ULIMIT_H 1

/* */
/* #undef HAVE_ULTRIX_SHADOW_PASSWORDS */

/* Define to 1 if you have the `umask' function. */
#define HAVE_UMASK 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <usersec.h> header file. */
/* #undef HAVE_USERSEC_H */

/* Define to 1 if you have the <utime.h> header file. */
#define HAVE_UTIME_H 1

/* Define to 1 if you have the <utmpx.h> header file. */
#define HAVE_UTMPX_H 1

/* Define to 1 if you have the <utmp.h> header file. */
#define HAVE_UTMP_H 1

/* Define to 1 if you have the `vhangup' function. */
#define HAVE_VHANGUP 1

/* Define to 1 if you have the `waitpid' function. */
#define HAVE_WAITPID 1

/* */
#define HAVE_ZLIB 1

/* Define to 1 if you have the `_getpty' function. */
/* #undef HAVE__GETPTY */

/* */
#define HOSTTYPE "i686-pc-linux-gnu"

/* */
/* #undef HPSUX7_KLUDGES */

/* */
/* #undef HPSUX_NONSTANDARD_X11_KLUDGE */

/* */
/* #undef KERBEROS */

/* */
/* #undef KERBEROS_TGT_PASSING */

/* */
/* #undef KRB5 */

/* Define if /var/adm/lastlog or whatever it is called is a directory (e.g.
   SGI IRIX). */
/* #undef LASTLOG_IS_DIR */

/* */
/* #undef LIBWRAP */

/* */
#define MAIL_SPOOL_DIRECTORY "/var/spool/mail"

/* */
/* #undef MAIL_SPOOL_FILE */

/* Define to 1 if `major', `minor', and `makedev' are declared in <mkdev.h>.
   */
/* #undef MAJOR_IN_MKDEV */

/* Define to 1 if `major', `minor', and `makedev' are declared in
   <sysmacros.h>. */
/* #undef MAJOR_IN_SYSMACROS */

/* */
/* #undef NEED_SYS_SYSLOG_H */

/* */
/* #undef NIS_PLUS */

/* */
/* #undef NOLOGIN_ALLOW */

/* */
/* #undef NONSTANDARD_IP_ADDRESS_X11_KLUDGE */

/* */
/* #undef O_NONBLOCK_BROKEN */

/* Name of package */
#define PACKAGE "sshbbs"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* */
#define PASSWD_PATH "/usr/bin/passwd"

/* */
/* #undef PATH_LOGIN */

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to use RSAREF. */
/* #undef RSAREF */

/* Define this to be the path of the rsh program to support executing rsh. */
#define RSH_PATH "/usr/kerberos/bin/rsh"

/* 1 */
/* #undef Raccept */

/* 1 */
/* #undef Rbind */

/* 1 */
/* #undef Rclose */

/* 1 */
/* #undef Rconnect */

/* 1 */
/* #undef Rdup */

/* 1 */
/* #undef Rdup2 */

/* 1 */
/* #undef Rfclose */

/* 1 */
/* #undef Rgethostbyname */

/* 1 */
/* #undef Rgetpeername */

/* 1 */
/* #undef Rgetsockname */

/* 1 */
/* #undef Rlisten */

/* 1 */
/* #undef Rread */

/* 1 */
/* #undef Rrecv */

/* 1 */
/* #undef Rrecvfrom */

/* 1 */
/* #undef Rrresvport */

/* 1 */
/* #undef Rselect */

/* 1 */
/* #undef Rsend */

/* 1 */
/* #undef Rsendto */

/* 1 */
/* #undef Rshutdown */

/* 1 */
/* #undef Rwrite */

/* */
/* #undef SCO */

/* */
/* #undef SCO5 */

/* */
/* #undef SECURE_NFS */

/* */
/* #undef SECURE_RPC */

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* */
/* #undef SOCKS */

/* */
/* #undef SOCKS4 */

/* */
/* #undef SOCKS5 */

/* */
/* #undef SPEED_T_IN_STDTYPES_H */

/* */
#define SSHD_NO_PORT_FORWARDING 1

/* */
#define SSHD_NO_X11_FORWARDING 1

/* Default path for lastlog. Determined by configure. */
#define SSH_LASTLOG 1

/* */
#define SSH_NO_PORT_FORWARDING 1

/* */
#define SSH_NO_X11_FORWARDING 1

/* Default path for utmp. Determined by configure. */
#define SSH_UTMP 1

/* Default path for wtmp. Determined by configure. */
#define SSH_WTMP 1

/* Define to 1 if the `S_IS*' macros in <sys/stat.h> do not work properly. */
/* #undef STAT_MACROS_BROKEN */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* 1 */
/* #undef TTY_GROUP */

/* */
/* #undef USELOGIN */

/* Define to use openssl library */
/* #undef USE_SSL */

/* */
/* #undef USE_STRLEN_FOR_AF_UNIX */

/* Version number of package */
#define VERSION "1.0"

/* */
/* #undef WITH_ARCFOUR */

/* */
#define WITH_BLOWFISH 1

/* */
/* #undef WITH_DES */

/* */
#define WITH_IDEA 1

/* */
/* #undef WITH_NONE */

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* 1 */
/* #undef X11_DIR */

/* Define this to be the path of the xauth program. */
#define XAUTH_PATH "/usr/bin/xauth"

/* Define to 1 if the X Window System is missing or not being used. */
#define X_DISPLAY_MISSING 1

/* Define if you need to in order for stat and other things to work. */
/* #undef _POSIX_SOURCE */

/* */
/* #undef __FreeBSD__ */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* 1 */
/* #undef crypt */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `int' if <sys/types.h> does not define. */
/* #undef mode_t */

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */


#endif /* KBS_SSH_CONFIG_H_INCLUDED */

